---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ghost-ds
  labels:
    app: cms
    author: micron
spec:
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      name: ghost-pod
      labels:
        app: cms
    spec:
      containers:
        - name: ghost-ds-cont
          image: ghost
          env:
            - name: NODE_ENV
              value: development
...
