---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: database
    author: micron
spec:
  replicas: 3
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: mydb
          image: postgres
          env:
            - name: POSTGRES_USER
              value: Sashank
            - name: POSTGRES_DB
              value: mydb
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: valueSample
...
              
