---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: proxy_server
    author: micron
spec:
  replicas: 3
  selector:
    matchLabels:
      app: proxy_server
  template:
    metadata:
      name: nginx-pod
      labels:
        app: proxy_server
    spec:
      containers:
        - name: mynginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 9090
            - containerPort: 443
              hostPort: 7897
...
