---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: front-end
    author: Sashank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      name: webapp-pod
      labels:
        app: front-end
    spec:
      containers:
        - name: adventour
          image: sashank0817/myfrontendapp:latest
...
