---
apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    app: database
    author: micron
spec:
  containers:
    - name: mydb
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: micron
...
