---
apiVersion: v1
kind: Pod
metadata:
  name: ghost-pod
  namespace: test-ns
  labels:
    app: cms
    author: micron
spec:
  containers:
    - name: cmsghost
      image: ghost
      env:
        - name: NODE_ENV
          value: development
      ports:
        - containerPort: 2368
          hostPort: 9090
...

