---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    techUsed: redis
    author: micron
spec:
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    techUsed: redis
    author: micron
...
#This is a change
