---
apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd-rc
  labels:
    app: server
    author: micron
spec:
  replicas: 3
  template:
    metadata:
      name: httpd-pod
      labels:
        app: server
    spec:
      containers:
        - name: myhttpd
          image: httpd
...
