---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    type: voting-app-service
    author: micron
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 70
      nodePort: 30007
  selector:
    techUsed: python
    author: micron
...

#This is a change

